### PR TITLE
Big Fat overhaul

### PR DESCRIPTION
**Pull request by saverofthewos**

### CODE REVIEW

**Comment by npxl32** [comment]
wait a moment hold on oh no-

**Comment by npxl32** [comment]
i was working on something big

**Comment by npxl32** [comment]
Wait nevermind I can adapt mine to work with yours.

**Comment by saverofthewos** [comment]
https://mido.readthedocs.io/en/latest/ @npxl32 learn

**Comment by npxl32** [comment]
not now

**Pull request merged**
